"""Country/city airport lookup maps for EasyTrip-Agent."""

country_aliases = {
    "United States": "USA",
    "United Kingdom": "UK",
    "Canada": "CAN",
    "Australia": "AUS",
    "New Zealand": "NZ",
    "South Africa": "SA",
    "India": "IND",
    "China": "CHN",
    "Japan": "JPN",
    "Korea": "KOR",
    "Malaysia": "MYS",
    "Singapore": "SGP",
    "Philippines": "PHL",
    "Vietnam": "VNM",
    "Indonesia": "IDN",
    "Spain": "ESP",
    "France": "FRA",
    "Germany": "DEU",
    "Italy": "ITA",
    "Netherlands": "NLD",
    "Belgium": "BEL",
    "Switzerland": "CHE",
    "Austria": "AUT",
    "Sweden": "SWE",
    "Norway": "NOR",
    "Denmark": "DNK",
    "Finland": "FIN",
    "Iceland": "ISL",
    "Ireland": "IRL",
    "Portugal": "PRT",
    "Greece": "GRC",
    "Turkey": "TUR",
    "Egypt": "EGY",
    "Argentina": "ARG",
    "Brazil": "BRA",
    "Chile": "CHL",
    "Colombia": "COL",
    "Mexico": "MEX",
    "Peru": "PER",
    "Venezuela": "VEN",
}

country_main_airports = {
    "USA": "LAX",
    "UK": "LON",
    "CAN": "YYZ",
    "AUS": "SYD",
    "NZ": "AKL",
    "SA": "JNB",
    "IND": "DEL",
    "CHN": "PEK",
    "JPN": "TYO",
    "KOR": "SEL",
    "MYS": "KUL",
    "SGP": "SIN",
    "PHL": "MNL",
    "VNM": "HAN",
    "IDN": "JKT",
    "ESP": "MAD",
    "FRA": "FRA",
    "DEU": "BER",
    "ITA": "ROM",
    "NLD": "AMS",
    "BEL": "BRU",
    "CHE": "ZRH",
    "AUT": "VIE",
    "SWE": "STO",
    "NOR": "OSL",
    "DNK": "CPH",
    "FIN": "HEL",
    "ISL": "REY",
    "IRL": "DUB",
    "PRT": "LIS",
    "GRC": "ATH",
    "TUR": "IST",
    "EGY": "CAI",
    "ARG": "EZE",
    "BRA": "GRU",
    "CHL": "SCL",
    "COL": "BOG",
    "MEX": "MEX",
    "PER": "LIM",
    "VEN": "CCS",
}

city_main_airports = {
    "Los Angeles": "LAX",
    "London": "LON",
    "Toronto": "YYZ",
    "Sydney": "SYD",
    "Auckland": "AKL",
    "Johannesburg": "JNB",
    "Delhi": "DEL",
    "Beijing": "PEK",
    "Tokyo": "TYO",
    "Seoul": "SEL",
    "Kuala Lumpur": "KUL",
    "Singapore": "SIN",
    "Manila": "MNL",
    "Hanoi": "HAN",
    "Jakarta": "JKT",
    "Madrid": "MAD",
    "Frankfurt": "FRA",
    "Berlin": "BER",
    "Rome": "ROM",
    "Amsterdam": "AMS",
    "Brussels": "BRU",
    "Zurich": "ZRH",
    "Vienna": "VIE",
    "Stockholm": "STO",
    "Oslo": "OSL",
    "Copenhagen": "CPH",
    "Helsinki": "HEL",
    "Reykjavik": "REY",
    "Dublin": "DUB",
    "Lisbon": "LIS",
    "Athens": "ATH",
    "Istanbul": "IST",
    "Cairo": "CAI",
    "Buenos Aires": "EZE",
    "Sao Paulo": "GRU",
    "Santiago": "SCL",
    "Bogota": "BOG",
    "Mexico City": "MEX",
    "Lima": "LIM",
    "Caracas": "CCS",
}
